# Generated by Django 4.2.1 on 2023-05-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_video_element',
            field=models.TextField(),
        ),
    ]
