# Generated by Django 4.2.1 on 2023-05-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0007_lecture_updated_at_register_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='register',
            name='updated_at',
        ),
    ]
