# Generated by Django 4.2.1 on 2023-05-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0009_register_created_at_register_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='register',
            name='updated_at',
        ),
    ]
